[build]
  command = "ng build --configuration=production"
  publish = "dist/upcountry-contractors/browser"

# SPA fallback so Angular routes work on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200